apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api
        image: mlops_hw_docker_compose_and_k8s-api:1
        env:
        - name: RABBIT_MQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: rmuser
        - name: RABBITMQ_PASS
          value: rmpassword
        - name: SQLALCHEMY_DATABASE_URI
          value: postgresql://admin:admin@postgres:5432/postgres
        - name: MODEL_QUEUE_NAME
          value: model_q
        - name: JOB_QUEUE_NAME
          value: job_q

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
    name: api
  selector:
    app: api-deployment