version: "3.9"
services:
  db_postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    networks:
      - network_db

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - network_rmq

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:admin@db_postgres:5432/postgres
      - RABBIT_MQ_HOST=rabbitmq
      - RABBITMQ_USER=rmuser
      - RABBITMQ_PASS=rmpassword
      - MODEL_QUEUE_NAME=model_q
      - JOB_QUEUE_NAME=job_q
    restart: always
    networks:
      - network_rmq
      - network_db

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBITMQ_USER=rmuser
      - RABBITMQ_PASS=rmpassword
      - MODEL_QUEUE_NAME=model_q
      - JOB_QUEUE_NAME=job_q
    restart: always
    networks:
      - network_rmq

networks:
  network_db:
    driver: bridge

  network_rmq:
    driver: bridge